apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-management-static-web-deployment
  namespace: dev-test
  labels:
    app: property-management-static-web
    version: 1.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: property-management-static-web
      version: 1.0.1
  template:
    metadata:
      labels:
        app: property-management-static-web
        version: 1.0.1
    spec:
      containers:
        - name: property-management-static-web
          image: 192.168.70.225/property-management-static-web:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: time-zone
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: time-zone
          hostPath:
            path: /etc/localtime
